# starts from a lightweight python image // slim -> strips out unnecessary stuff to keep the image small
FROM python:3.11-slim

# Set the working directory in the container to /app
WORKDIR /app

# Copy the requirements first, before the rest of the code. This allows Docker to cache the installed dependencies, so if you change your code but not your dependencies, Docker can skip the installation step and speed up the build process.
COPY app/requirements.txt .

# Install the dependencies inside the container
RUN pip install --no-cache-dir -r requirements.txt

# copies your actual code into the container. This should be done after installing dependencies to take advantage of Docker's layer caching.
COPY app/ .

# documents that the app runs on port 8000, which is the default port for FastAPI applications
EXPOSE 8000

# command that runs when the container starts
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]